//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        public int RequestId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public string FoodDescription { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public System.DateTime MaxPreserveTime { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
